<a href="https://colab.research.google.com/github/omprakaxh/python-DE-practice/blob/master/Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chiptole.tsv'
chipo = pd.read_csv(url,sep='\t')

In [10]:
chipo.head(10)
#To see the first n column's use head function

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [11]:
chipo.shape[0]
# shape give's the number of entries

4622

In [15]:
chipo.shape[1]

5

In [17]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [18]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

In [20]:
quantity = chipo.groupby('item_name')
quantity = quantity.sum()
quantity = quantity.sort_values(['quantity'],ascending=False)
quantity.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [21]:
choice = chipo.groupby('choice_description').sum()
choice = choice.sort_values(['quantity'],ascending=False)
choice.head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

In [22]:
total = chipo.quantity.sum()
total

np.int64(4972)

In [23]:
chipo.item_price.dtype

dtype('O')

In [24]:
dollarizer = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(dollarizer)

In [25]:
chipo.item_price.dtype

dtype('float64')

In [26]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [31]:
kaasu = chipo.quantity * chipo.item_price
kaasu = round(kaasu.sum(),2)
kaasu
#

np.float64(39237.02)

In [34]:
chipo.order_id.value_counts().count()

np.int64(1834)

In [36]:
average = chipo.quantity * chipo.item_price
average = average.sum() / 1834
average

np.float64(21.39423118865867)

In [38]:
chipo.item_name.value_counts().count()

np.int64(50)