In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('sales_activity.csv')
df

   OrderID Product Region  Quantity  Price     Month
0     1001  Laptop  North         2  50000   January
1     1002   Phone  South         5  20000   January
2     1003  Tablet   East         3  15000  February
3     1004  Laptop   West         1  50000  February
4     1005   Phone  North         4  20000     March
5     1006  Tablet  South         2  15000     March
6     1007  Laptop   East         3  50000     April
7     1008   Phone   West         6  20000     April
8     1009  Tablet  North         1  15000       May
9     1010  Laptop  South         2  50000       May

In [5]:
df['Revenue'] = df['Quantity'] * df['Price']
df

   OrderID Product Region  Quantity  Price     Month  Revenue
0     1001  Laptop  North         2  50000   January   100000
1     1002   Phone  South         5  20000   January   100000
2     1003  Tablet   East         3  15000  February    45000
3     1004  Laptop   West         1  50000  February    50000
4     1005   Phone  North         4  20000     March    80000
5     1006  Tablet  South         2  15000     March    30000
6     1007  Laptop   East         3  50000     April   150000
7     1008   Phone   West         6  20000     April   120000
8     1009  Tablet  North         1  15000       May    15000
9     1010  Laptop  South         2  50000       May   100000

In [9]:
df.groupby('Region')['Revenue'].agg('sum')

Region
East     195000
North    195000
South    230000
West     170000
Name: Revenue, dtype: int64

In [12]:
df.groupby('Product')['Revenue'].agg("sum")

Product
Laptop    400000
Phone     300000
Tablet     90000
Name: Revenue, dtype: int64

In [13]:
df

   OrderID Product Region  Quantity  Price     Month  Revenue
0     1001  Laptop  North         2  50000   January   100000
1     1002   Phone  South         5  20000   January   100000
2     1003  Tablet   East         3  15000  February    45000
3     1004  Laptop   West         1  50000  February    50000
4     1005   Phone  North         4  20000     March    80000
5     1006  Tablet  South         2  15000     March    30000
6     1007  Laptop   East         3  50000     April   150000
7     1008   Phone   West         6  20000     April   120000
8     1009  Tablet  North         1  15000       May    15000
9     1010  Laptop  South         2  50000       May   100000

In [14]:
df.groupby('Month')['Revenue'].agg("sum")

Month
April       270000
February     95000
January     200000
March       110000
May         115000
Name: Revenue, dtype: int64

In [15]:
month_order = ["January", "February", "March", "April", "May"]

result = df.groupby("Month")["Revenue"].sum()
result = result.reindex(month_order)  # ✅ reorder by correct month sequence
print(result)

Month
January     200000
February     95000
March       110000
April       270000
May         115000
Name: Revenue, dtype: int64

In [16]:
df

   OrderID Product Region  Quantity  Price     Month  Revenue
0     1001  Laptop  North         2  50000   January   100000
1     1002   Phone  South         5  20000   January   100000
2     1003  Tablet   East         3  15000  February    45000
3     1004  Laptop   West         1  50000  February    50000
4     1005   Phone  North         4  20000     March    80000
5     1006  Tablet  South         2  15000     March    30000
6     1007  Laptop   East         3  50000     April   150000
7     1008   Phone   West         6  20000     April   120000
8     1009  Tablet  North         1  15000       May    15000
9     1010  Laptop  South         2  50000       May   100000

In [23]:
# Step 1 - Total revenue per region
total_revenue = df.groupby("Region")["Revenue"].sum()

# Step 2 - Best product per region (product with highest revenue)
best_product = df.loc[df.groupby("Region")["Revenue"].idxmax()].set_index("Region")["Product"]

# Step 3 - Combine into a new DataFrame
summary = pd.DataFrame({
    "Total Revenue": total_revenue,
    "Best Product": best_product
}).reset_index()

print(summary)

# Step 4 - Save to CSV
summary.to_csv("sales_summary.csv", index=False)
print("✅ sales_summary.csv saved!")

  Region  Total Revenue Best Product
0   East         195000       Laptop
1  North         195000       Laptop
2  South         230000        Phone
3   West         170000        Phone
✅ sales_summary.csv saved!